baseurl = "."
languageCode = "en-us"
title = "Nix Theme"
theme = "hugo-theme-nix"

[params]
  GithubID = "your_github"
  TwitterID = "your_twitter"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "your_name"
  HeaderUsername = "username"
  HeaderHostname = "hostname"
  Email = "your_email"
  About = "info_about_you"
  ProfilePicture = "https://pbs.twimg.com/profile_images/485564678039302144/Fjxv6IbQ.png"
  GoogleAnalytics = "your_google_analytics_id"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
